COLUMNA_CLIENTES_NOMBRE = 0
COLUMNA_CLIENTES_DIRECCION = 1
COLUMNA_CLIENTES_DOCUMENTO = 2
COLUMNA_CLIENTES_FECHA_ALTA = 3
COLUMNA_CLIENTES_CORREO = 4
COLUMNA_CLIENTES_EMPRESA = 5

COLUMNA_VIAJES_DOCUMENTO = 0
COLUMNA_VIAJES_FECHA = 1
COLUMNA_VIAJES_MONTO = 2